### ISSUE TITLE
Conflict with Blueprint Extensions

### ISSUE THREAD

**Issue by avpas** [LuziferSenpai/Electronic-Locomotives#1]
Hello,

Following your last update, there is this error message when I try to load my game that uses both this mod **and** Blueprint Extensions. I have posted the error in dewiniaid's mod as well, since I am not sure who is at fault. (Well ok, the error showed up after your changes, but I do not want to assume anything since assumption is the mother of all failures...)
`The mod Blueprint Extensions caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlueprintExtensions::on_configuration_changed
The mod Electronic Locomotives caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Electronic_Locomotives::on_surface_created (ID 61)
Electronic_Locomotives/scripts/Events.lua:220: bad argument #1 of 2 to 'next' (table expected, got nil)
stack traceback:
[C]: in function 'next'
Electronic_Locomotives/scripts/Events.lua:220: in function 'MainGUIUpdateProviderList'
Electronic_Locomotives/scripts/Events.lua:506: in function 'handler'
core/lualib/event_handler.lua:44: in function <core/lualib/event_handler.lua:42>
stack traceback:
BlueprintExtensions/modules/landfill.lua:53: in function 'compute_prototype_overrides'
BlueprintExtensions/modules/landfill.lua:126: in function '?'
BlueprintExtensions/control.lua:60: in function 'call_module_methods'
BlueprintExtensions/control.lua:96: in function <BlueprintExtensions/control.lua:93>
stack traceback:
[C]: in function 'create_surface'
BlueprintExtensions/modules/landfill.lua:53: in function 'compute_prototype_overrides'
BlueprintExtensions/modules/landfill.lua:126: in function '?'
BlueprintExtensions/control.lua:60: in function 'call_module_methods'
BlueprintExtensions/control.lua:96: in function <BlueprintExtensions/control.lua:93>`

**Comment by LuziferSenpai** [comment]
Will be fixed in the next Update.

**Comment by avpas** [comment]
Fix Confirmed.
