### ISSUE TITLE
Bug with Factorio release 0.17.70 (build 47440, win64, steam)

### ISSUE THREAD

**Issue by avpas** [LuziferSenpai/Electronic-Locomotives#3]
Hello, latest release, loaded the savegame, got:
`The mod Electronic Locomotives caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Electronic_Locomotives::on_surface_deleted (ID 62)
__Electronic_Locomotives__/scripts/Events.lua:517: bad argument #2 of 2 to 'table_size' (table expected, got nil)
stack traceback:
	[C]: in function 'table_size'
	__Electronic_Locomotives__/scripts/Events.lua:517: in function 'handler'
	__core__/lualib/event_handler.lua:44: in function <__core__/lualib/event_handler.lua:42>`

**Comment by LuziferSenpai** [comment]
Fixed in the next Release.
