### ISSUE TITLE
When using a filter - i get unknown keys

### ISSUE THREAD

**Issue by Trblz42** [LuziferSenpai/Electronic-Locomotives#4]
Factorio 0.18.5 with version 0.3.5 of your mod

When I want to define a filter in a filter inserter, i get Unknown key: "item-name.electronic-fuel-01"  and Unknown Key:"fuel-category-name.eletronic" 

See my screenshot

![ElectronicMotors_FilterView](https://user-images.githubusercontent.com/18010439/74300543-f989ff80-4d04-11ea-93ad-d94b724578d9.png)

**Comment by LuziferSenpai** [comment]
That is not a Bug, I just didnt made a Name or a Fuel Category Name, because its just a item, to improve UPS in my MOD.
