### ISSUE TITLE
Event handler crashes in combination with VortK's Deep Core Mining

### ISSUE THREAD

**Issue by jinks** [LuziferSenpai/Electronic-Locomotives#5]
This line
https://github.com/LuziferSenpai/Electronic-Locomotives/blob/f5e91d682552620c157e6d42633b4ef8c2412c95/scripts/Events.lua#L439
assumes that every created entity will have a unit number, but Deep Core Mining creates ore patch entities on the resource_depleted event which obviously don't.

A simple nil check should fix that crash.

**Comment by LuziferSenpai** [comment]
I need the Error Message, pls.

**Comment by LuziferSenpai** [comment]
Fixed in 0.3.6
