### ISSUE TITLE
Latest update breaks AAi Vehicles: Warden

### ISSUE THREAD

**Issue by jinks** [LuziferSenpai/Electronic-Locomotives#6]
It appears you're doing something with sprites you didn't do before...
```
108.958 Mods to disable:Failed to load mods: The given sprite rectangle (left_top=0x0, right_bottom=32x32) is outside the actual sprite size (left_top=0x0, right_bottom=22x22).: __Electronic_Locomotives__/graphics/electric.png

Mods to be disabled:
• aai-vehicles-warden (0.4.2)
```

I haven't looked at your code, but this seems like something is going wrong when you're trying to add the electric icon to a vehicle?

**Comment by LuziferSenpai** [comment]
That is a problem in Earandel's code. This will break with every item that doesnt have a 32x32 sprite. So report it to him and tell him: **"Dont expect every item icon to be 32x32"** from me.
