### ISSUE TITLE
Error when adding a new locomotive to the rails

### ISSUE THREAD

**Issue by BenderMTB** [LuziferSenpai/Electronic-Locomotives#8]
Error when adding a new locomotive to the rails. The latest version of the mod and related mods is installed

![error](https://github.com/LuziferSenpai/Electronic-Locomotives/assets/174050617/d2fccd2a-ff80-4e3e-a065-668021f7a39e)

**Comment by LuziferSenpai** [comment]
Did you migrate from a older version or did you use a fresh install?
And when yes, which version?

And do you have a mod list for me?

**Comment by LuziferSenpai** [comment]
Is fixed with Version 2.0.1

**Comment by BenderMTB** [comment]
Thank you!
