### ISSUE TITLE
Equipment grid support

### ISSUE THREAD

**Issue by BenderMTB** [LuziferSenpai/Electronic-Locomotives#9]
Please add support for the equipment grid (12*12) so that you can place additional electric motors for acceleration. Cargo trains have a high top speed but are slow to accelerate.
I don't remember if this is in the classic version of the game. I'm playing the mod Crastorio 2 + Space Exploration

**Comment by LuziferSenpai** [comment]
Will not happen, with 2.0.3 acceleration is fixed. I forgot to give the cargo locomotive a better max_power.
